// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'core/models/encrypted_image_model.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
      id: const obx_int.IdUid(1, 7388705639705382051),
      name: 'EncryptedImageModel',
      lastPropertyId: const obx_int.IdUid(6, 30771881794749912),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 3788877228797684672),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 1035816133165507797),
            name: 'dateCreated',
            type: 10,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 9099485455770869085),
            name: 'encryptedImagePath',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 6325651024734885010),
            name: 'imageName',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 1455104596737687097),
            name: 'originalImagePath',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 30771881794749912),
            name: 'originalImageExtension',
            type: 9,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[])
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore(
    {String? directory,
    int? maxDBSizeInKB,
    int? maxDataSizeInKB,
    int? fileMode,
    int? maxReaders,
    bool queriesCaseSensitiveDefault = true,
    String? macosApplicationGroup}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(getObjectBoxModel(),
      directory: directory ?? (await defaultStoreDirectory()).path,
      maxDBSizeInKB: maxDBSizeInKB,
      maxDataSizeInKB: maxDataSizeInKB,
      fileMode: fileMode,
      maxReaders: maxReaders,
      queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
      macosApplicationGroup: macosApplicationGroup);
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
      entities: _entities,
      lastEntityId: const obx_int.IdUid(1, 7388705639705382051),
      lastIndexId: const obx_int.IdUid(0, 0),
      lastRelationId: const obx_int.IdUid(0, 0),
      lastSequenceId: const obx_int.IdUid(0, 0),
      retiredEntityUids: const [],
      retiredIndexUids: const [],
      retiredPropertyUids: const [],
      retiredRelationUids: const [],
      modelVersion: 5,
      modelVersionParserMinimum: 5,
      version: 1);

  final bindings = <Type, obx_int.EntityDefinition>{
    EncryptedImageModel: obx_int.EntityDefinition<EncryptedImageModel>(
        model: _entities[0],
        toOneRelations: (EncryptedImageModel object) => [],
        toManyRelations: (EncryptedImageModel object) => {},
        getId: (EncryptedImageModel object) => object.id,
        setId: (EncryptedImageModel object, int id) {
          object.id = id;
        },
        objectToFB: (EncryptedImageModel object, fb.Builder fbb) {
          final encryptedImagePathOffset =
              fbb.writeString(object.encryptedImagePath);
          final imageNameOffset = fbb.writeString(object.imageName);
          final originalImagePathOffset =
              fbb.writeString(object.originalImagePath);
          final originalImageExtensionOffset =
              fbb.writeString(object.originalImageExtension);
          fbb.startTable(7);
          fbb.addInt64(0, object.id);
          fbb.addInt64(1, object.dateCreated.millisecondsSinceEpoch);
          fbb.addOffset(2, encryptedImagePathOffset);
          fbb.addOffset(3, imageNameOffset);
          fbb.addOffset(4, originalImagePathOffset);
          fbb.addOffset(5, originalImageExtensionOffset);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final dateCreatedParam = DateTime.fromMillisecondsSinceEpoch(
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 6, 0));
          final imageNameParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 10, '');
          final encryptedImagePathParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 8, '');
          final originalImagePathParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 12, '');
          final originalImageExtensionParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 14, '');
          final object = EncryptedImageModel(
              dateCreated: dateCreatedParam,
              imageName: imageNameParam,
              encryptedImagePath: encryptedImagePathParam,
              originalImagePath: originalImagePathParam,
              originalImageExtension: originalImageExtensionParam)
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

          return object;
        })
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [EncryptedImageModel] entity fields to define ObjectBox queries.
class EncryptedImageModel_ {
  /// See [EncryptedImageModel.id].
  static final id =
      obx.QueryIntegerProperty<EncryptedImageModel>(_entities[0].properties[0]);

  /// See [EncryptedImageModel.dateCreated].
  static final dateCreated =
      obx.QueryDateProperty<EncryptedImageModel>(_entities[0].properties[1]);

  /// See [EncryptedImageModel.encryptedImagePath].
  static final encryptedImagePath =
      obx.QueryStringProperty<EncryptedImageModel>(_entities[0].properties[2]);

  /// See [EncryptedImageModel.imageName].
  static final imageName =
      obx.QueryStringProperty<EncryptedImageModel>(_entities[0].properties[3]);

  /// See [EncryptedImageModel.originalImagePath].
  static final originalImagePath =
      obx.QueryStringProperty<EncryptedImageModel>(_entities[0].properties[4]);

  /// See [EncryptedImageModel.originalImageExtension].
  static final originalImageExtension =
      obx.QueryStringProperty<EncryptedImageModel>(_entities[0].properties[5]);
}
